/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#e3e2e0",
        "on-surface": "#241919",
        "surface-tint": "#5e5f5d",
        "on-tertiary-fixed": "#2f1316",
        "secondary-fixed-dim": "#debfc2",
        "tertiary-container": "#fff7f6",
        "on-secondary-fixed": "#281719",
        "primary": "#5e5f5d",
        "outline-variant": "#c5c7c3",
        "error": "#ba1a1a",
        "inverse-primary": "#c7c6c4",
        "on-secondary-fixed-variant": "#574144",
        "surface-container": "#ffe9e8",
        "inverse-surface": "#3a2d2d",
        "secondary-fixed": "#fbdbde",
        "primary-fixed-dim": "#c7c6c4",
        "outline": "#757874",
        "on-error": "#ffffff",
        "surface-bright": "#fff8f7",
        "surface": "#fff8f7",
        "primary-container": "#faf9f6",
        "on-background": "#241919",
        "surface-container-high": "#f9e3e3",
        "tertiary-fixed-dim": "#ebbabd",
        "surface-dim": "#ead5d5",
        "on-primary": "#ffffff",
        "surface-container-highest": "#f3dedd",
        "secondary": "#70585b",
        "on-secondary-container": "#755d5f",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#ffedec",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffdadb",
        "background": "#fff8f7",
        "on-primary-fixed-variant": "#464745",
        "secondary-container": "#f8d8db",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#727270",
        "on-tertiary-fixed-variant": "#603d40",
        "on-tertiary-container": "#90686b",
        "surface-variant": "#f3dedd",
        "surface-container-low": "#fff0f0",
        "on-surface-variant": "#444844",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#1a1c1a",
        "tertiary": "#7a5457"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-max-width": "1120px",
        "unit": "8px",
        "gutter": "24px",
        "stack-md": "24px",
        "margin-page": "64px",
        "stack-lg": "48px",
        "stack-sm": "12px"
      },
      fontFamily: {
        "label-sm": ["Montserrat"],
        "headline-lg": ["Playfair Display"],
        "body-sm": ["Montserrat"],
        "headline-md": ["Playfair Display"],
        "label-lg": ["Montserrat"],
        "display-lg": ["Playfair Display"],
        "headline-sm": ["Playfair Display"],
        "body-lg": ["Montserrat"],
        "body-md": ["Montserrat"],
        "headline-lg-mobile": ["Playfair Display"]
      },
      fontSize: {
        "label-sm": ["10px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "headline-lg": ["40px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "500"}],
        "label-lg": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600"}],
        "display-lg": ["56px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-sm": ["24px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
